### ISSUE TITLE
Incorrect after plugin

### ISSUE THREAD

**Issue by flpandre** [klevu/productsearch#96]
The plugin defined at `Klevu\Search\Plugin\CatalogRule\Model\Indexer\IndexBuilder\ReindexByIdsPlugin::afterReindexByIds` ([check the file here](https://github.com/klevu/productsearch/blob/3.x/Plugin/CatalogRule/Model/Indexer/IndexBuilder/ReindexByIdsPlugin.php#L34)) expects that `Magento\CatalogRule\Model\Indexer\IndexBuilder::reindexByIds` return an array, but that method has a void return type. ([check the file here](https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/CatalogRule/Model/Indexer/IndexBuilder.php#L290)) 

Then, magento reindex fails with:

`Klevu\Search\Plugin\CatalogRule\Model\Indexer\IndexBuilder\ReindexByIdsPlugin::afterReindexByIds(): Argument #2 ($productIds) must be of type array, null given`

The specific reindex error case I'm getting is this:

- Set `catalogrule_product` to run by schedule
  - `bin/magento indexer:set-mode schedule catalogrule_product`
- Make any changes to product rules to generate backlog items on `catalogrule_product`
- Run the cron
- Check `cron_schedule` table with the error.

I used magerun to execute specifically `indexer_update_all_views` which was where I found the plugin error.
` n98 sys:cron:run indexer_update_all_views`.

**Comment by sandipklevu** [comment]
Hi Andre,

Thanks for reaching out to us.

There was a known bug which was fixed in the 3.4.1/2.12.1 release last September where second argument $result was missing and added in that release.
 
[Release notes for 3.4.1](https://github.com/klevu/klevu-smart-search-M2/releases/tag/3.4.1) 

See [diff](https://github.com/klevu/productsearch/commit/188ee38cef6ccd0928944629d780a3864d856d58#diff-ae769253cd87d065f0e5d8050c433b724f99212f189654a21d6322479b125868):

Can you confirm if this is the same in your case, if yes then upgrade the module will handle it.
If not then please share any description, preconditions and environment and other additional information to [Contact Support](https://help.klevu.com/support/tickets/new).

**Comment by flpandre** [comment]
Thank you, that seems to be the case.
